# https://docs.docker.com/build/ci/github-actions/examples/
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  IMAGE_NAME: "brpaz/commitlint"
  COMMITLINT_VERSION: "17.4.4"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: error

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          outputs: type=docker,dest=/tmp/myimage.tar
          push: false
          tags: ${{env.IMAGE_NAME}}:${{ github.sha }}

      - name: Load image
        run: |
          docker load -i /tmp/myimage.tar
          docker image ls -a

      - name: Setup container structure tests
        run: |
          curl -fsLO https://storage.googleapis.com/container-structure-test/v1.14.0/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
          container-structure-test version

      - name: Run tests
        run: |
          container-structure-test test --image ${{env.IMAGE_NAME}}:${{ github.sha }} --config structure-tests.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
          retention-period: 1

  publish:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: Load image
        run: |
          docker load -i /tmp/myimage.tar
          docker image ls -a

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/brpaz/commitlint
            brpaz/commitlint
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,enable=true,priority=200,value=${{ env.COMMITLINT_VERSION }}
            type=sha
          labels: |
            org.opencontainers.image.title=Commitlint
            org.opencontainers.image.description=A Docker Image for Commitlint
            org.opencontainers.image.vendor=Bruno Paz

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Set release commit message
        id: release_commit_message
        run: |
          echo "commit_message=chore(release): bump version ${VERSION}" >> $GITHUB_OUTPUT

      - name: Commit updated Changelog and Package.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "${{ steps.release_commit_message.outputs.commit_message }}"
          file_pattern: "CHANGELOG.md"
