# https://docs.docker.com/build/ci/github-actions/examples/
name: Release

on:
  workflow_call:
    inputs:
      commitlint_version:
        type: string
        description: "The version of commitlint to use"
        required: true
        default: "19.3.0"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

  workflow_dispatch:
    inputs:
      commitlint_version:
        description: "The version of commitlint to use"
        required: true
        default: "19.3.0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_IMAGE_NAME: "commitlint:test"
  COMMITLINT_VERSION: ${{ github.event.inputs.commitlint_version }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/brpaz/commitlint
            brpaz/commitlint
          tags: |
            type=raw,enable=true,priority=200,value=${{ env.COMMITLINT_VERSION }}
            type=raw,value=latest,enable={{is_default_branch}}

          labels: |
            org.opencontainers.image.title=Commitlint
            org.opencontainers.image.description=A Docker Image for Commitlint
            org.opencontainers.image.url=https://github.com/brpaz/docker-commitlint

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: ${{ env.TEST_IMAGE_NAME }}
          build-args: |
            COMMITLINT_VERSION: ${{ env.COMMITLINT_VERSION }}

      - name: Run container tests
        uses: brpaz/structure-tests-action@1.2.0
        with:
          image: ${{env.TEST_IMAGE_NAME}}
          configFile: structure-tests.yaml

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMITLINT_VERSION: ${{ env.COMMITLINT_VERSION }}
