name: Weekly Docker Build

on:
  schedule:
    - cron: "0 11 * * 0" # Every Sunday at 11 AM
  workflow_dispatch:

jobs:
  check-latest-commitlint-version:
    name: Check latest commitlint version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Get latest commitlint version
        id: get-version
        run: |
          VERSION=$(npm show commitlint version)
          echo $VERSION
          echo "name=commitlint_version::$VERSION" >> $GITHUB_OUTPUT

      - name: Get tags from Package registry
        shell: bash
        run: |
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          TAG=${{ steps.get-version.outputs.commitlint_version }}

          echo $TAG

          node scripts/has-tag.js
          if [ $? -ne 1 ]; then
            echo "name=exists::true" >> $GITHUB_OUTPUT
          fi

          echo "name=exists::false" >> $GITHUB_OUTPUT
      - name: Trigger image build
        # if: steps.get-version.outputs.exists == 'false'
        uses: ./.github/workflows/release.yml
        with:
          commitlint_version: ${{ steps.get-version.outputs.commitlint_version }}
