name: Weekly Docker Build

on:
  schedule:
    - cron: "0 11 * * 0" # Every Sunday at 11 AM
  workflow_dispatch:

jobs:
  check-latest-commitlint-version:
    name: Check latest commitlint version
    runs-on: ubuntu-latest
    outputs:
      trigger_build: ${{ steps.get-tags.outputs.trigger_build }}
      commitlint_version: ${{ steps.get-version.outputs.commitlint_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Get latest commitlint version
        id: get-version
        run: |
          VERSION=$(npm show commitlint version)
          echo $VERSION
          echo "commitlint_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get tags from Package registry
        id: get-tags
        shell: bash
        run: |
          export GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          export TAG=${{ steps.get-version.outputs.commitlint_version }}

          node scripts/has-tag.js
          status=$?
          echo $status
          if [ $status -eq 2 ]; then
              echo "trigger_build=true" >> $GITHUB_OUTPUT
          elif [ $status -eq 0 ]; then
            echo "version already exists in registry, skipping build"
            echo "trigger_build=true" >> $GITHUB_OUTPUT
          else
            echo "Script failed with exit status $status"
            exit $status
          fi

  trrigger-build:
    if: needs.check-latest-commitlint-version.outputs.trigger_build == 'true'
    needs: check-latest-commitlint-version
    permissions:
      packages: write
    uses: brpaz/docker-commitlint/.github/workflows/release.yml@main
    with:
      commitlint_version: ${{ needs.check-latest-commitlint-version.outputs.commitlint_version }}
