name: Security Scanning
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  TEST_IMAGE_NAME: "brpaz/my-image"
jobs:
  security-scanning:
    name: Security Scanning
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: |
            ${{ env.TEST_IMAGE_NAME }}:${{ github.sha }}

      - run: docker image ls
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.TEST_IMAGE_NAME }}:${{ github.sha }}
          format: "table"
          exit-code: "1"
          vuln-type: "os,library"
          output: "trivy-results.txt"
          severity: "CRITICAL,HIGH"

      - name: Vulnerabilities found
        uses: peter-evans/create-issue-from-file@v3
        if: failure()
        with:
          title: Security vulnerabilities found
          content-filepath: ./trivy-results.txt
          labels: security
          assignees: brpaz
          token: ${{ secrets.GITHUB_TOKEN }}
